// ------------------------------------------------------------------------
// ========================================================================
// THIS CODE AND INFORMATION ARE GENERATED BY AUTOMATIC CODE GENERATOR
// ========================================================================
// Template:   	IDataSource.tt
// Version:		2.0
using System.CodeDom.Compiler;
using System.Collections.ObjectModel;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using Entities = WPAppStudio.Entities;
using EntitiesBase = WPAppStudio.Entities.Base;
using WPAppStudio.Shared;

namespace WPAppStudio.Repositories
{
    /// <summary>
    /// Pictures_FlickrPics interface.
    /// </summary>
    [CompilerGenerated]
    [GeneratedCode("Radarc", "4.0")]
    public interface IPictures_FlickrPics
    {
        Task<ObservableCollection<EntitiesBase.FlickrSearchResult>> GetData();
        Task<ObservableCollection<EntitiesBase.FlickrSearchResult>> Refresh();
		Task<ObservableCollection<EntitiesBase.FlickrSearchResult>> Search(FilterSpecification filter);
		Task<EntitiesBase.FlickrSearchResult> Previous(EntitiesBase.FlickrSearchResult current);
		Task<EntitiesBase.FlickrSearchResult> Next(EntitiesBase.FlickrSearchResult current);
    }
}
