// ------------------------------------------------------------------------
// ========================================================================
// THIS CODE AND INFORMATION ARE GENERATED BY AUTOMATIC CODE GENERATOR
// ========================================================================
// Template:   	DataSource.tt
// Version:		2.0
using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Data.Linq;
using System.Linq;
using System.Runtime.CompilerServices;
using System.ServiceModel.Syndication;
using System.Text;
using System.Threading.Tasks;
using EntitiesBase = WPAppStudio.Entities.Base;
using IServices = WPAppStudio.Services.Interfaces;
using RepositoriesBase = WPAppStudio.Repositories.Base;
using WPAppStudio.Shared;

namespace WPAppStudio.Repositories
{
    /// <summary>
    /// Flickr data source.
    /// </summary>
    [CompilerGenerated]
    [GeneratedCode("Radarc", "4.0")]
    public class Pictures_FlickrPics : IPictures_FlickrPics 
    {
		private static bool AlreadyAccessed = false;
        private RepositoriesBase.IXmlDataSource _xmlDataSource; 
	    private IServices.IStorageService _storageService;
        private IServices.IInternetService _internetService;

		private const string FlickrUri = "http://api.flickr.com/services/feeds/photos_public.gne?{0}={1}";
		private const string FlickrQuery = @"93527926@N06";
		private const string FlickrQueryType = "id";

        /// <summary>
        /// Initializes a new instance of the <see cref="Pictures_FlickrPics" /> class.
        /// </summary>
        /// <param name="xmlDataSource">A XML based data source.</param>
		/// <param name="internetService">Internet service.</param>
        /// <param name="storageService">Storage service.</param>
        public Pictures_FlickrPics(RepositoriesBase.IXmlDataSource xmlDataSource, IServices.IInternetService internetService, IServices.IStorageService storageService)
        {
            _xmlDataSource = xmlDataSource;
		    _storageService = storageService;
            _internetService = internetService;
        }

        /// <summary>
        /// Retrieves the cached data from Flickr public data source (Query: 93527926@N06), in an observable collection of FlickrSearchResult items.
        /// </summary>
        /// <returns>An observable collection of FlickrSearchResult items.</returns>
        public async Task<ObservableCollection<EntitiesBase.FlickrSearchResult>> GetData()
        {
			if(!AlreadyAccessed)
			{
				AlreadyAccessed = true;
				return await Refresh();
			}
			
            var data = LoadData();
            return data != null && data.Any() ? data : await Refresh();
        }

        /// <summary>
        /// Retrieves the data from Flickr public data source (Query: 93527926@N06), in an observable collection of FlickrSearchResult items.
        /// </summary>
        /// <returns>An observable collection of FlickrSearchResult items.</returns>
        public async Task<ObservableCollection<EntitiesBase.FlickrSearchResult>> Refresh()
        {
            SyndicationFeed feed;
			
			if (_internetService.IsNetworkAvailable())
            {
				feed = await _xmlDataSource.LoadRemote<System.ServiceModel.Syndication.SyndicationFeed>(String.Format(FlickrUri, FlickrQueryType, FlickrQuery));
				var items = feed != null ? new ObservableCollection<EntitiesBase.FlickrSearchResult>(feed.Items.Select(i=>new EntitiesBase.FlickrSearchResult(i))) : new ObservableCollection<EntitiesBase.FlickrSearchResult>();
				_storageService.Save("Pictures_FlickrPics", items);
				
				return items;
			}
				
			return _storageService.Load<ObservableCollection<EntitiesBase.FlickrSearchResult>>("Pictures_FlickrPics");
        }
						
		/// <summary>
        /// Retrieves the data from Flickr public data source (Query: 93527926@N06), filtered by a filter specification, in an observable collection of FlickrSearchResult items.
        /// </summary>
		/// <param name="filter">Filter operation specification</param>
        /// <returns>An observable collection of FlickrSearchResult items.</returns>
        public async Task<ObservableCollection<EntitiesBase.FlickrSearchResult>> Search(FilterSpecification filter)
        {
			var data = await GetData();
            return RepositoriesBase.Filter<EntitiesBase.FlickrSearchResult>.FilterCollection(filter, data);
        }
		
		/// <summary>
        /// Checks if data source has a element before the passed as parameter
        /// </summary>
		/// <param name="current">Current element</param>
        /// <returns>True, if there is a previous element, false if there is not</returns>
		public async Task<bool> HasPrevious(EntitiesBase.FlickrSearchResult current)
        {
			var data = await GetData();
			
            if (current == null || !data.Any()) return false;

            return data.IndexOf(current) > 0;
        }
		
		/// <summary>
        /// Checks if data source has a element after the passed as parameter
        /// </summary>
		/// <param name="current">Current element</param>
        /// <returns>True, if there is a next element, false if there is not</returns>
		public async Task<bool> HasNext(EntitiesBase.FlickrSearchResult current)
        {
			var data = await GetData();
			
            if (current == null || !data.Any()) return false;

            return data.IndexOf(current) < data.Count - 1;
        }
		
		/// <summary>
        /// Retrieves the previous element from source.
        /// </summary>
		/// <param name="current">Current element</param>
        /// <returns>The previous element from items, if it exists. Otherwise, returns null</returns>
        public async Task<EntitiesBase.FlickrSearchResult> Previous(EntitiesBase.FlickrSearchResult current)
        {
			var data = await GetData();
		
            if (current == null || !data.Any()) return null;

            var index = data.IndexOf(current);

            if (index == 0 || index == -1) return null;

            return data[index - 1];
        }
		
		/// <summary>
        /// Retrieves the next element from source.
        /// </summary>
		/// <param name="current">Current element</param>
        /// <returns>The next element from items, if it exists. Otherwise, returns null</returns>
        public async Task<EntitiesBase.FlickrSearchResult> Next(EntitiesBase.FlickrSearchResult current)
        {
			var data = await GetData();
			
            if (current == null || !data.Any()) return null;

            var index = data.IndexOf(current);

		    if (index == -1 || index == data.Count - 1) return null;

            return data[index + 1];
        }

        private ObservableCollection<EntitiesBase.FlickrSearchResult> LoadData()
        {
			return _storageService.Load<ObservableCollection<EntitiesBase.FlickrSearchResult>>("Pictures_FlickrPics");
        }
	}	
}

