// ------------------------------------------------------------------------
// ========================================================================
// THIS CODE AND INFORMATION ARE GENERATED BY AUTOMATIC CODE GENERATOR
// ========================================================================
// Template:   	IViewModel.tt
// Version:		2.0
using System.CodeDom.Compiler;
using System.Collections.ObjectModel;
using System.Runtime.CompilerServices;
using System.Windows;
using System.Windows.Input;
using Entities = WPAppStudio.Entities;
using EntitiesBase = WPAppStudio.Entities.Base;

namespace WPAppStudio.ViewModel.Interfaces
{
    /// <summary>
    /// Pictures_Detail ViewModel interface.
    /// </summary>
    [CompilerGenerated]
    [GeneratedCode("Radarc", "4.0")]
    public interface IPictures_DetailViewModel
    {		
        /// <summary>
        /// Gets/Sets the CurrentFlickrSearchResult property.
        /// </summary>
		EntitiesBase.FlickrSearchResult CurrentFlickrSearchResult { get; set; }
        /// <summary>
        /// Gets/Sets the HasNextpanoramaPictures_Detail0 property.
        /// </summary>
		bool HasNextpanoramaPictures_Detail0 { get; set; }
        /// <summary>
        /// Gets/Sets the HasPreviouspanoramaPictures_Detail0 property.
        /// </summary>
		bool HasPreviouspanoramaPictures_Detail0 { get; set; }
        
        /// <summary>
        /// Gets the TextToSpeechPictures_DetailStaticControlCommand command.
        /// </summary>
		ICommand TextToSpeechPictures_DetailStaticControlCommand { get; }

        
        /// <summary>
        /// Gets the SharePictures_DetailStaticControlCommand command.
        /// </summary>
		ICommand SharePictures_DetailStaticControlCommand { get; }

        
        /// <summary>
        /// Gets the PinToStartPictures_DetailStaticControlCommand command.
        /// </summary>
		ICommand PinToStartPictures_DetailStaticControlCommand { get; }

        
        /// <summary>
        /// Gets the NextpanoramaPictures_Detail0 command.
        /// </summary>
		ICommand NextpanoramaPictures_Detail0 { get; }

        
        /// <summary>
        /// Gets the PreviouspanoramaPictures_Detail0 command.
        /// </summary>
		ICommand PreviouspanoramaPictures_Detail0 { get; }

	}
}
